// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://swagger.json` | (string & {});
};

export type EventMessageTypeModel = 'Default' | 'Info' | 'Error' | 'Success' | 'Warning';

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown | string | null | string | null | number | null | string | null | string | null | undefined;
};

export type ReindexRequestModel = {
    rebuildIndex: boolean;
};

export type ReindexState = 'Idle' | 'Running' | 'Failed';

export type ReindexStatus = {
    indexAlias: string;
    state: ReindexState;
    rebuildIndex: boolean;
    processedItems: number;
    totalItems?: number | null;
    startedAt?: string | null;
    completedAt?: string | null;
    errorMessage?: string | null;
};

export type ReindexData = {
    body?: ReindexRequestModel;
    path: {
        indexAlias: string;
    };
    query?: never;
    url: '/umbraco/search-examine-reindex/api/v1/index/{indexAlias}/reindex';
};

export type ReindexErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Conflict
     */
    409: ReindexStatus;
};

export type ReindexError = ReindexErrors[keyof ReindexErrors];

export type ReindexResponses = {
    /**
     * OK
     */
    200: ReindexStatus;
};

export type ReindexResponse = ReindexResponses[keyof ReindexResponses];

export type GetReindexStatusData = {
    body?: never;
    path: {
        indexAlias: string;
    };
    query?: never;
    url: '/umbraco/search-examine-reindex/api/v1/index/{indexAlias}/reindex/status';
};

export type GetReindexStatusErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type GetReindexStatusResponses = {
    /**
     * OK
     */
    200: ReindexStatus;
};

export type GetReindexStatusResponse = GetReindexStatusResponses[keyof GetReindexStatusResponses];
