// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44310/' | (string & {});
};

export type ProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number | string;
    detail?: null | string;
    instance?: null | string;
};

export type ReindexRequestModel = {
    rebuildIndex: boolean;
};

export type ReindexState = 'Idle' | 'Running' | 'Failed';

export type ReindexStatus = {
    indexAlias: string;
    state: ReindexState;
    rebuildIndex: boolean;
    processedItems: number | string;
    totalItems: null | number | string;
    startedAt: null | string;
    completedAt: null | string;
    errorMessage: null | string;
};

export type ReindexData = {
    body: ReindexRequestModel;
    path: {
        indexAlias: string;
    };
    query?: never;
    url: '/umbraco/search-examine-reindex/api/v1/index/{indexAlias}/reindex';
};

export type ReindexErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Conflict
     */
    409: ReindexStatus;
};

export type ReindexError = ReindexErrors[keyof ReindexErrors];

export type ReindexResponses = {
    /**
     * OK
     */
    200: ReindexStatus;
};

export type ReindexResponse = ReindexResponses[keyof ReindexResponses];

export type GetReindexStatusData = {
    body?: never;
    path: {
        indexAlias: string;
    };
    query?: never;
    url: '/umbraco/search-examine-reindex/api/v1/index/{indexAlias}/reindex/status';
};

export type GetReindexStatusErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type GetReindexStatusResponses = {
    /**
     * OK
     */
    200: ReindexStatus;
};

export type GetReindexStatusResponse = GetReindexStatusResponses[keyof GetReindexStatusResponses];
