<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <StaticWebAssetBasePath>/</StaticWebAssetBasePath>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Umbraco.Cms.Search.Provider.Examine" />
    <PackageReference Include="Umbraco.Cms.Api.Management" />
  </ItemGroup>

</Project>
